import os

import dotenv

dotenv.load_dotenv()


DATABASE_URL=os.getenv("DATABASE_URL")
ACCESS_TOKEN_EXPIRE_TIME_MINUTES=os.getenv("ACCESS_TOKEN_EXPIRE_TIME_MINUTES")
REFRESH_TOKEN_EXPIRE_TIME_DAYS=os.getenv("REFRESH_TOKEN_EXPIRE_TIME_DAYS")
ACCESS_TOKEN_SECRET_KEY=os.getenv("ACCESS_TOKEN_SECRET_KEY")
REFRESH_TOKEN_SECRET_KEY=os.getenv("REFRESH_TOKEN_SECRET_KEY")
